import React, { useState } from 'react';
import { View, Text, SafeAreaView, TouchableOpacity, ScrollView, TextInput } from '../components/ReactNativeShim';
import { ArrowLeft, Sparkles, RefreshCw, ChevronRight, Briefcase, CheckCircle, Info, AlertCircle, Calendar } from '../components/Icons';
import { FormattedMessage } from '../components/FormattedMessage';
import { Download, Copy, Check, FileText, Printer, Share2, BookOpen, Rocket, ShieldCheck, Target } from 'lucide-react';
import { useAppState } from '../services/state';
import { BottomNav } from '../components/BottomNav';

interface SideHustleIdea {
  name: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  startupCost: string;
  timeRequired: string;
  whyMatches: string;
  steps: string[];
  challenges: string;
  resources: string;
}

const exportBlueprintPDF = (hustleName: string = 'Side Hustle', markdownText: string = '') => {
  const safeText = markdownText || '';
  if (!safeText) return;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export the PDF report.');
    return;
  }

  const htmlContent = safeText
    .replace(/^# (.*$)/gim, '<h1 class="main-title">$1</h1>')
    .replace(/^## (.*$)/gim, '<h2 class="section-title">$1</h2>')
    .replace(/^### (.*$)/gim, '<h3 class="sub-title">$1</h3>')
    .replace(/^\* \*\*(.*?)\*\*:? (.*$)/gim, '<li><strong>$1:</strong> $2</li>')
    .replace(/^\* (.*$)/gim, '<li>$1</li>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/^(\d+)\. \*\*(.*?)\*\*:? (.*$)/gim, '<li class="numbered"><strong>$2:</strong> $3</li>')
    .replace(/^(\d+)\. (.*$)/gim, '<li class="numbered">$2</li>')
    .replace(/^---/gim, '<hr />')
    .replace(/\n\n/g, '</p><p>');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${hustleName} - Complete Side Hustle Blueprint</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
          body {
            font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
          }
          .header {
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .main-title {
            font-size: 26px;
            font-weight: 700;
            color: #0f172a;
            margin-bottom: 8px;
          }
          .section-title {
            font-size: 18px;
            font-weight: 700;
            color: #0284c7;
            margin-top: 28px;
            margin-bottom: 12px;
            border-bottom: 1px solid #f1f5f9;
            padding-bottom: 6px;
          }
          .sub-title {
            font-size: 15px;
            font-weight: 600;
            color: #1e293b;
            margin-top: 18px;
            margin-bottom: 8px;
          }
          p {
            margin-bottom: 12px;
            font-size: 14px;
            color: #334155;
          }
          ul, ol {
            margin-top: 6px;
            margin-bottom: 16px;
            padding-left: 24px;
          }
          li {
            font-size: 14px;
            margin-bottom: 8px;
            color: #334155;
          }
          strong {
            color: #0f172a;
          }
          hr {
            border: 0;
            border-top: 1px solid #e2e8f0;
            margin: 24px 0;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            font-size: 11px;
            color: #64748b;
            text-align: center;
          }
          @media print {
            body { padding: 20px; }
            .section-title { page-break-after: avoid; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="main-title">${hustleName}</h1>
          <p style="color: #64748b; font-size: 13px;">Complete A-to-Z Implementation Blueprint &bull; Prepared by Orbit AI</p>
        </div>
        <div>
          ${htmlContent}
        </div>
        <div class="footer">
          Generated by Orbit AI &bull; Complete Implementation Blueprint for ${hustleName}
        </div>
        <script>
          window.onload = () => {
            setTimeout(() => {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
};

const generateComprehensiveFallbackBlueprint = (
  hustle: SideHustleIdea,
  skills: string,
  interests: string,
  hoursPerWeek: string,
  budget: string,
  country: string
): string => {
  const hustleName = hustle?.name || 'Side Hustle Venture';
  const whyMatches = hustle?.whyMatches || 'This business matches your profile and provides strong market demand with manageable startup requirements.';
  const startupCost = hustle?.startupCost || 'Low startup cost (R0 - R500)';
  const challenges = hustle?.challenges || 'Finding initial clients and managing time efficiently.';
  const resources = hustle?.resources || 'Canva, LinkedIn, Upwork, Google Workspace, and relevant industry forums.';

  const stepList = (hustle?.steps && Array.isArray(hustle.steps) && hustle.steps.length > 0)
    ? hustle.steps.map((s, idx) => `* **Step ${idx + 1}:** ${s || ''}`).join('\n')
    : `* **Step 1:** Define your specific package offering and target pricing.\n* **Step 2:** Set up a simple 1-page digital portfolio or PDF overview.\n* **Step 3:** Establish a professional payment gateway and invoice template.\n* **Step 4:** Send direct outreach messages to 15 target customers or local businesses.\n* **Step 5:** Deliver initial trial work with high quality and speed.\n* **Step 6:** Collect written client testimonials and referrals.\n* **Step 7:** Reinvest initial earnings into digital tools and scaling.`;

  return `# ${hustleName} — Complete Step-by-Step Implementation Blueprint

---

## 1. What The Business Is
${hustleName} is a high-value, practical venture where you provide structured services or solutions to clients in **${country || 'your local market'}**. This business operates with low overhead and allows you to monetize your skills in **${skills || 'professional service delivery'}** while serving customers who need reliable, high-quality results.

---

## 2. Why It Is A Good Opportunity
* **Growing Market Demand:** Businesses and individuals in ${country || 'the region'} are actively seeking dependable specialists to solve immediate problems.
* **Low Barrier to Entry:** You can launch this business from home with minimal upfront capital and start generating revenue within weeks.
* **Personalized Fit:** ${whyMatches}

---

## 3. Skills Required
* **Core Technical Competency:** Mastery of the primary service deliverables (${skills || 'communication, organization, and technical execution'}).
* **Client Communication & Negotiation:** Clear written and verbal communication to set realistic expectations and agree on project scope.
* **Basic Financial Tracking:** Ability to issue invoices, record expenses, and follow up on client payments promptly.
* **Skill Acquisition Strategy:** Fill any immediate skill gaps within 48 hours using free resources on YouTube, Coursera, or HubSpot Academy.

---

## 4. Equipment Required
* **Hardware:** Reliable computer/laptop or smartphone with a stable internet connection.
* **Software & Communication Suite:** Standard workspace tools (Google Drive, Docs, Sheets), messaging apps (WhatsApp Business, Zoom, Google Meet), and basic PDF converters.
* **Workspace:** Quiet home desk or dedicated working area for focused execution and professional client video calls.

---

## 5. Estimated Startup Costs
* **Target Budget Category:** **${startupCost}** (tailored to your selected budget range of **${budget}**).
* **Digital Footprint (R0 – R250):** Free digital portfolio platforms (LinkedIn, Canva, Notion) or an optional custom domain name.
* **Software & Productivity Tools (R0 – R300):** Free tiers of Canva, Google Workspace, and communication apps.
* **Marketing & Client Acquisition (R0 – R500):** Direct personal networking and word-of-mouth outreach require zero financial spend.
* **Total Estimated Initial Cash Outlay:** Under ${startupCost} — ultra-low financial risk with rapid profitability potential.

---

## 6. Where To Get Supplies Or Products
* **Digital Platforms & Tools:** Access official free tiers from verified providers (Canva, Notion, Google Workspace, Wave Accounting).
* **Wholesalers / Vendor Partners (if physical):** Partner directly with reputable local suppliers or print-on-demand providers in ${country}.
* **Recommended Learning & Tools Directory:** ${resources}

---

## 7. How To Find Customers
* **Direct Community & Business Outreach:** Identify 20 local businesses, colleagues, or professionals in ${country} who need this service and contact them with a tailored message.
* **Freelance Marketplaces & Directories:** List your profile on Upwork, LinkedIn, Fiverr, and regional service directories.
* **Warm Network Activation:** Send an introductory message to your existing contacts letting them know your new service is live and open for bookings.
* **First Client Launch Incentive:** Offer a limited-time **20% launch discount** to your first 3 clients in exchange for a written review and testimonial.

---

## 8. How To Market The Business
* **Educational Content Marketing:** Share helpful tips, short case studies, and before-and-after project examples 3 times per week on LinkedIn, Instagram, or Facebook.
* **1-Page Digital Portfolio:** Build a clean PDF overview or Notion page showcasing 3 sample deliverables.
* **Value-First Community Engagement:** Answer questions in online forums, Facebook groups, and industry communities without aggressive sales pitches.
* **Referral Flywheel:** Offer existing clients a **10% discount or referral reward** for every new paying customer they introduce.

---

## 9. How To Receive Payments
* **Supported Payment Gateways:** Set up professional payment links using **PayFast, Yoco, Stripe, or direct bank EFT transfers**.
* **Invoicing Best Practices:** Always issue a formal digital invoice with clear payment terms before starting work.
* **Upfront Deposit Policy (Critical):** Require a **50% upfront deposit** prior to commencing work, with the remaining 50% due upon completion and final delivery.
* **Financial Tracking:** Maintain a dedicated spreadsheet or use free accounting software (e.g., Wave) to log every invoice, payment, and expense.

---

## 10. Common Mistakes To Avoid
* **Underpricing Your Value:** Never compete purely on lowest price; charge based on reliability, quality, and the value of results delivered.
* **Over-Investing Before Revenue:** Do not spend money on expensive logos, branding agencies, or paid ads until you have closed your first 3 paying clients.
* **Scope Creep Without Pay:** Always define the exact project deliverables in writing so clients do not demand unpaid extra work.
* **Anticipated Challenge & Mitigation:** ${challenges} — Overcome this by communicating proactively and setting clear milestones early.

---

## 11. AI Tools That Can Help
* **Orbit AI:** Use Orbit AI to draft client proposals, email templates, service agreements, and engaging social media marketing copy.
* **ChatGPT / Claude:** Excellent for brainstorming service packages, refining project outlines, and troubleshooting technical questions.
* **Canva AI:** Create professional social media graphics, flyers, and client presentations in minutes.
* **Grammarly:** Ensure every client email, report, and proposal is grammatically pristine and highly professional.

---

## 12. Expected Timeline Before Earning Income
* **Week 1 (Days 1–7): Foundation & Offer Ready:** Service packages defined, sample portfolio completed, and payment method configured.
* **Week 2 (Days 8–14): First Lead & Outreach:** Direct outreach generates initial client inquiries and discovery calls.
* **Week 3 (Days 15–21): First Paying Client:** Closing first contract, securing 50% deposit, and delivering initial project.
* **Month 2+ (Days 30–60): Stable Recurring Revenue:** Repeat clients, referrals, and retainer contracts establish consistent monthly income.

---

## 13. Tips For Growing And Scaling The Business
* **Package Your Services:** Move away from hourly billing to structured monthly retainers or high-value project packages.
* **Systematize & Automate:** Build reusable templates for client onboarding, invoicing, and project delivery to save time.
* **Raise Rates Gradually:** Increase your rates by **15–20%** for every 5 successful client deliveries as your reputation grows.
* **Outsource Repetitive Tasks:** Hire junior freelancers or virtual assistants to handle administrative tasks so you can focus on sales and high-level strategy.

---

## 14. Step-by-Step Action Plan (Launch Roadmap)

### Week 1: Setup & Core Offer
1. **Define Your Package:** Write down your exact service offering, pricing structure, and turnaround time.
2. **Setup Payments:** Register your business account on PayFast, Yoco, or set up a dedicated bank account for EFT receipts.
3. **Build Sample Work:** Create 2–3 high-quality portfolio examples or demo projects to show potential clients.
4. **Create Outreach Script:** Draft a concise, professional message explaining how your service helps clients save time or make money.

### Week 2: Initial Client Outreach & Market Testing
1. **Contact Warm Leads:** Reach out to 10 people in your personal or professional network who might need this service or know someone who does.
2. **Direct Cold Outreach:** Send 15 tailored messages to local businesses or target clients on LinkedIn/social media.
3. **Join Communities:** Actively participate in 3 online groups where your target customers spend time.
4. **Offer Launch Special:** Propose a discounted trial rate for your first 2 clients in exchange for a detailed review.

### Week 3: Closing & Delivering Your First Project
1. **Conduct Consultations:** Hold professional 15-minute discovery calls with interested leads.
2. **Secure Deposit:** Send a formal invoice and collect your first 50% upfront payment before work begins.
3. **Over-Deliver Quality:** Execute the project with exceptional attention to detail and daily progress updates.
4. **Request Testimonial:** Upon completion and receipt of final payment, ask the client for a 3-sentence written recommendation.

### Week 4: Systematizing & Marketing Expansion
1. **Publish Case Study:** Share your first successful client project and testimonial across your social media channels.
2. **Establish Daily Habit:** Dedicate 30 minutes every day strictly to lead generation and client follow-ups.
3. **Refine Pricing:** Review your time spent versus income earned and adjust your package rates accordingly.
4. **Plan Month 2 Growth:** Set a goal for 3 recurring monthly clients and automate your invoicing workflow.`;
};

export const SideHustleScreen: React.FC = () => {
  const { setMobileScreen } = useAppState();

  // Form input states
  const [skills, setSkills] = useState('');
  const [interests, setInterests] = useState('');
  const [hoursPerWeek, setHoursPerWeek] = useState('10');
  const [budget, setBudget] = useState('R0 - R500');
  const [country, setCountry] = useState('South Africa');

  // App UI states
  const [loading, setLoading] = useState(false);
  const [ideas, setIdeas] = useState<SideHustleIdea[]>([]);
  const [selectedHustle, setSelectedHustle] = useState<SideHustleIdea | null>(null);
  const [errorMessage, setErrorMessage] = useState('');

  // Blueprint cache & states
  const [blueprints, setBlueprints] = useState<Record<string, string>>({});
  const [loadingBlueprint, setLoadingBlueprint] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!skills.trim()) {
      setErrorMessage('Please describe your skills.');
      return;
    }
    if (!interests.trim()) {
      setErrorMessage('Please describe your interests.');
      return;
    }

    setErrorMessage('');
    setLoading(true);
    setIdeas([]);
    setSelectedHustle(null);

    try {
      const response = await fetch('/api/side-hustles', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          skills,
          interests,
          hoursPerWeek: `${hoursPerWeek} hours per week`,
          budget,
          country,
          internetAccess: 'Yes',
          smartphoneAccess: 'Yes',
          laptopAccess: 'Yes'
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(errorText || `HTTP error! Status: ${response.status}`);
      }

      const data = await response.json();
      if (data.ideas && Array.isArray(data.ideas)) {
        setIdeas(data.ideas);
      } else {
        throw new Error(data.error || 'Failed to generate ideas.');
      }
    } catch (err: any) {
      setErrorMessage(err.message || 'An error occurred during generation. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenBlueprint = async (hustle: SideHustleIdea) => {
    if (!hustle) return;
    setSelectedHustle(hustle);
    setCopied(false);

    const hustleKey = hustle.name || 'Side Hustle';

    if (blueprints[hustleKey]) {
      return;
    }

    setLoadingBlueprint(true);
    try {
      const initialStepsText = Array.isArray(hustle.steps) ? hustle.steps.join('; ') : '';
      const prompt = `Generate a complete step-by-step implementation blueprint from A to Z for starting the side hustle: "${hustleKey}" in ${country || 'your market'}.
The user has the following profile:
- Skills/Strengths: ${skills || 'General'}
- Interests: ${interests || 'Varies'}
- Available Time: ${hoursPerWeek || '10'} hours per week
- Available Budget: ${budget || 'Low'}
- Difficulty: ${hustle.difficulty || 'Moderate'}
- Estimated Startup Cost: ${hustle.startupCost || 'Low'}
- Why It Matches: ${hustle.whyMatches || ''}
- Initial Steps: ${initialStepsText}
- Anticipated Challenges: ${hustle.challenges || ''}
- Recommended Resources: ${hustle.resources || ''}

You must provide a comprehensive, beautifully formatted business guide in Markdown with clear headings, numbered steps, bullet points, proper spacing, and professional typography.
Include EVERY ONE of the following required sections in exact order:
1. What the business is
2. Why it is a good opportunity
3. Skills required
4. Equipment required
5. Estimated startup costs
6. Where to get supplies or products
7. How to find customers
8. How to market the business
9. How to receive payments
10. Common mistakes to avoid
11. AI tools that can help
12. Expected timeline before earning income
13. Tips for growing and scaling the business
14. Step-by-Step Action Plan (a clear roadmap from Week 1 to Week 4+ with concrete actions for each week)`;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 12000); // 12 second timeout before fallback

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: prompt,
          systemPrompt: "You are the Orbit AI Senior Business Consultant and Enterprise Startup Advisor. You generate complete, highly detailed A-to-Z business implementation blueprints in clean Markdown format with professional headers, bullet points, and actionable timelines. Do not use emojis.",
          history: []
        }),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (response.ok) {
        const data = await response.json();
        if (data.reply && data.reply.trim().length > 300) {
          setBlueprints(prev => ({ ...prev, [hustleKey]: data.reply }));
          setLoadingBlueprint(false);
          return;
        }
      }
    } catch (err) {
      console.warn("API Blueprint generation fallback triggered:", err);
    }

    // Fallback to our comprehensive A-to-Z implementation blueprint
    const fallbackMarkdown = generateComprehensiveFallbackBlueprint(hustle, skills, interests, hoursPerWeek, budget, country);
    setBlueprints(prev => ({ ...prev, [hustleKey]: fallbackMarkdown }));
    setLoadingBlueprint(false);
  };

  const currentBlueprintMarkdown = selectedHustle
    ? (blueprints[selectedHustle.name || 'Side Hustle'] || generateComprehensiveFallbackBlueprint(selectedHustle, skills, interests, hoursPerWeek, budget, country))
    : '';

  const handleCopyBlueprint = () => {
    if (!currentBlueprintMarkdown) return;
    navigator.clipboard?.writeText(currentBlueprintMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handleExportPDF = () => {
    if (!selectedHustle || !currentBlueprintMarkdown) return;
    exportBlueprintPDF(selectedHustle.name, currentBlueprintMarkdown);
  };

  return (
    <SafeAreaView id="side_hustle_screen" className="bg-white flex flex-col h-full justify-between">
      {/* HEADER BAR */}
      <View className="px-6 py-4 bg-white border-b border-slate-100 flex flex-row items-center justify-between select-none">
        <View className="flex flex-row items-center gap-3">
          <TouchableOpacity 
            onClick={() => {
              if (selectedHustle) {
                setSelectedHustle(null);
              } else {
                setMobileScreen('chat');
              }
            }}
            className="p-2 hover:bg-slate-100 rounded-full text-slate-600 cursor-pointer transition"
          >
            <ArrowLeft className="w-5 h-5" />
          </TouchableOpacity>
          <Text className="text-base font-semibold text-slate-900 tracking-tight">
            {selectedHustle ? 'Complete Implementation Blueprint' : 'AI Side Hustle Generator'}
          </Text>
        </View>
        <TouchableOpacity
          onClick={() => setMobileScreen('chat')}
          className="px-3 py-1.5 bg-white hover:bg-slate-100/80 text-slate-700 border border-slate-200/80 rounded-full flex flex-row items-center gap-1.5 transition cursor-pointer select-none active:scale-95 shrink-0"
        >
          <Text className="text-xs font-medium text-slate-700">Chat</Text>
        </TouchableOpacity>
      </View>

      <ScrollView className="flex-1 bg-white p-6" contentContainerClassName="max-w-3xl mx-auto w-full space-y-8 pb-12">
        {selectedHustle ? (
          /* COMPLETE STEP-BY-STEP IMPLEMENTATION BLUEPRINT VIEW */
          <View className="space-y-6 animate-fade-in text-left">
            {/* Header block with Badges & Actions */}
            <View className="space-y-4 pb-6 border-b border-slate-200">
              <View className="flex flex-row flex-wrap items-center justify-between gap-4">
                <Text className="text-3xl font-bold text-slate-900 font-sans tracking-tight leading-tight flex-1">
                  {selectedHustle.name}
                </Text>
                
                {/* Top Action Buttons */}
                <View className="flex flex-row items-center gap-2">
                  <TouchableOpacity
                    onClick={handleCopyBlueprint}
                    className="px-4 py-2 bg-slate-100 hover:bg-slate-200 rounded-xl flex flex-row items-center gap-1.5 text-xs font-semibold text-slate-800 transition cursor-pointer select-none"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-700" />}
                    <Text>{copied ? 'Copied' : 'Copy Guide'}</Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                    onClick={handleExportPDF}
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg flex flex-row items-center gap-1.5 text-xs font-medium transition cursor-pointer select-none shadow-sm"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    <Text className="text-xs font-medium text-white">PDF</Text>
                  </TouchableOpacity>
                </View>
              </View>
              
              {/* Sleek Metadata Badges */}
              <View className="flex flex-row flex-wrap items-center gap-2">
                <span className="px-3 py-1 rounded-full bg-slate-100 text-xs font-semibold text-slate-800">
                  Difficulty: {selectedHustle.difficulty}
                </span>
                <span className="px-3 py-1 rounded-full bg-blue-50 text-xs font-semibold text-blue-800">
                  Est. Startup Cost: {selectedHustle.startupCost}
                </span>
                <span className="px-3 py-1 rounded-full bg-emerald-50 text-xs font-semibold text-emerald-800">
                  Time Commitment: {selectedHustle.timeRequired}
                </span>
              </View>
            </View>

            {/* Loading Blueprint Indicator */}
            {loadingBlueprint ? (
              <View className="py-16 flex flex-col items-center justify-center text-center space-y-4">
                <View className="p-4 bg-blue-50 rounded-full animate-pulse">
                  <RefreshCw className="w-8 h-8 text-blue-600 animate-spin" />
                </View>
                <View className="space-y-1">
                  <Text className="text-lg font-semibold text-slate-900">
                    Creating Your Complete Implementation Blueprint...
                  </Text>
                  <Text className="text-sm text-slate-500 max-w-md">
                    Structuring A-to-Z business model, financial requirements, marketing strategies, AI tools, and Week 1–4+ Action Plan for {selectedHustle.name}...
                  </Text>
                </View>
              </View>
            ) : (
              /* Render Full Beautiful Formatted Blueprint */
              <View className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 space-y-6">
                <FormattedMessage text={currentBlueprintMarkdown} message={currentBlueprintMarkdown} />
              </View>
            )}

            {/* Bottom Document Actions */}
            <View className="pt-6 border-t border-slate-100 flex flex-row flex-wrap items-center justify-between gap-4">
              <TouchableOpacity
                onClick={() => setSelectedHustle(null)}
                className="px-5 py-2.5 bg-slate-100 hover:bg-slate-200 rounded-lg font-medium text-slate-800 text-xs cursor-pointer transition select-none flex flex-row items-center gap-2"
              >
                <ArrowLeft className="w-3.5 h-3.5" />
                <Text className="text-xs font-medium text-slate-800">Back to Ideas</Text>
              </TouchableOpacity>
              <View className="flex flex-row items-center gap-2.5">
                <TouchableOpacity
                  onClick={handleCopyBlueprint}
                  className="px-3.5 py-2 border border-slate-200 hover:border-slate-300 rounded-lg font-medium text-slate-700 text-xs cursor-pointer transition select-none flex flex-row items-center gap-1.5"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-600" />}
                  <Text className="text-xs font-medium text-slate-700">{copied ? 'Copied Guide' : 'Copy Report'}</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  onClick={handleExportPDF}
                  className="px-3.5 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium text-white text-xs cursor-pointer transition select-none flex flex-row items-center gap-1.5 shadow-sm"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <Text className="text-xs font-medium text-white">Export PDF</Text>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        ) : (
          /* MAIN SEARCH & RESULTS SCREEN - SLEEK & MINIMAL */
          <View className="space-y-8 text-left">
            {/* HERO TITLE BLOCK */}
            <View className="space-y-2">
              <Text className="text-3xl font-bold text-slate-900 tracking-tight font-sans">
                AI Side Hustle Generator
              </Text>
              <Text className="text-base text-slate-600 leading-relaxed font-sans">
                Tell us about your background, availability, and resources to receive a tailored, realistic venture blueprint.
              </Text>
            </View>

            {/* INPUT PANEL - APPLE / CHATGPT CLEAN FORM STYLE */}
            <View className="space-y-5">
              {errorMessage && (
                <View className="p-4 bg-red-50 border border-red-200 rounded-xl flex flex-row items-center gap-2.5">
                  <AlertCircle className="w-4 h-4 text-red-600 shrink-0" />
                  <Text className="text-sm text-red-700 font-medium leading-tight">{errorMessage}</Text>
                </View>
              )}

              {/* Skills Input */}
              <View className="space-y-2">
                <label className="text-xs font-semibold text-slate-700 uppercase tracking-wider">What are your skills or strengths?</label>
                <input
                  type="text"
                  value={skills}
                  onChange={(e) => setSkills(e.target.value)}
                  placeholder="e.g. Writing, basic accounting, graphic design, tutoring, driving..."
                  className="w-full px-4 py-3.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-sm placeholder:text-slate-400 focus:outline-none focus:border-blue-600 transition font-sans"
                />
              </View>

              {/* Interests Input */}
              <View className="space-y-2">
                <label className="text-xs font-semibold text-slate-700 uppercase tracking-wider">What interests or topics do you enjoy?</label>
                <input
                  type="text"
                  value={interests}
                  onChange={(e) => setInterests(e.target.value)}
                  placeholder="e.g. Fitness, gaming, fashion, food, technology, education..."
                  className="w-full px-4 py-3.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-sm placeholder:text-slate-400 focus:outline-none focus:border-blue-600 transition font-sans"
                />
              </View>

              <View className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Hours Available Per Week */}
                <View className="space-y-2">
                  <label className="text-xs font-semibold text-slate-700 uppercase tracking-wider">Time available per week</label>
                  <select
                    value={hoursPerWeek}
                    onChange={(e) => setHoursPerWeek(e.target.value)}
                    className="w-full px-4 py-3.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-sm focus:outline-none focus:border-blue-600 transition font-sans cursor-pointer"
                  >
                    <option value="5">5 hours per week (Minimal)</option>
                    <option value="10">10 hours per week (Part-time)</option>
                    <option value="20">20 hours per week (Medium)</option>
                    <option value="40">40+ hours per week (Full-time)</option>
                  </select>
                </View>

                {/* Startup Budget */}
                <View className="space-y-2">
                  <label className="text-xs font-semibold text-slate-700 uppercase tracking-wider">Available startup budget</label>
                  <select
                    value={budget}
                    onChange={(e) => setBudget(e.target.value)}
                    className="w-full px-4 py-3.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-sm focus:outline-none focus:border-blue-600 transition font-sans cursor-pointer"
                  >
                    <option value="R0 - R500">R0 - R500 (No/Low cost)</option>
                    <option value="R500 - R2000">R500 - R2000 (Low investment)</option>
                    <option value="R2000 - R10000">R2000 - R10000 (Moderate)</option>
                    <option value="R10000+">R10000+ (High investment)</option>
                  </select>
                </View>
              </View>

              {/* Country */}
              <View className="space-y-2">
                <label className="text-xs font-semibold text-slate-700 uppercase tracking-wider">Country or Region</label>
                <input
                  type="text"
                  value={country}
                  onChange={(e) => setCountry(e.target.value)}
                  placeholder="e.g. South Africa, Kenya, Nigeria..."
                  className="w-full px-4 py-3.5 rounded-xl bg-white border border-slate-200 text-slate-900 text-sm placeholder:text-slate-400 focus:outline-none focus:border-blue-600 transition font-sans"
                />
              </View>

              {/* Generate Button - SLEEK ORBIT BLUE BUTTON */}
              <View className="pt-2">
                <TouchableOpacity
                  onClick={handleGenerate}
                  disabled={loading}
                  className={`w-full py-4 rounded-xl flex flex-row items-center justify-center gap-2.5 transition cursor-pointer select-none font-medium text-sm text-white ${
                    loading ? 'bg-blue-400' : 'bg-blue-600 hover:bg-blue-700 active:scale-[0.99]'
                  }`}
                >
                  {loading ? (
                    <>
                      <RefreshCw className="w-4 h-4 text-white animate-spin" />
                      <Text className="text-white font-medium">Generating...</Text>
                    </>
                  ) : (
                    <Text className="text-white font-medium">Generate Side Hustle Ideas</Text>
                  )}
                </TouchableOpacity>
              </View>
            </View>

            {/* RESULTS LIST OF HUSTLES - APPLE/LINEAR CLEAN CARDS */}
            {ideas.length > 0 && (
              <View className="space-y-4 pt-6 border-t border-slate-100">
                <Text className="text-xs font-semibold text-slate-500 uppercase tracking-wider block">
                  Recommended Opportunities ({ideas.length})
                </Text>

                <View className="space-y-4">
                  {ideas.map((hustle, idx) => (
                    <View key={idx} className="bg-white p-6 border border-slate-200 hover:border-slate-300 rounded-2xl space-y-4 transition">
                      <View className="flex flex-row items-start justify-between gap-4">
                        <Text className="text-lg font-semibold text-slate-900 tracking-tight block">
                          {hustle.name}
                        </Text>
                        <span className="text-xs px-2.5 py-1 rounded-full bg-slate-100 font-medium text-slate-700 shrink-0">
                          {hustle.difficulty}
                        </span>
                      </View>

                      {/* Subtle Metadata row */}
                      <View className="flex flex-row items-center gap-6 text-xs text-slate-500">
                        <Text>
                          Est. Cost: <span className="font-semibold text-slate-800">{hustle.startupCost}</span>
                        </Text>
                        <Text>
                          Time: <span className="font-semibold text-slate-800">{hustle.timeRequired}</span>
                        </Text>
                      </View>

                      {/* Rationale description */}
                      <Text className="text-sm text-slate-600 leading-relaxed font-sans">
                        {hustle.whyMatches}
                      </Text>

                      {/* Action Buttons - REQUIRED BLUEPRINT & GUIDE BUTTONS ON EVERY SIDE HUSTLE */}
                      <View className="pt-3 flex flex-row flex-wrap items-center justify-end gap-2 border-t border-slate-100">
                        <TouchableOpacity
                          onClick={() => handleOpenBlueprint(hustle)}
                          className="px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-700 font-semibold text-xs rounded-xl flex flex-row items-center gap-1.5 transition cursor-pointer select-none"
                        >
                          <BookOpen className="w-3.5 h-3.5" />
                          <Text>View Blueprint</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          onClick={() => handleOpenBlueprint(hustle)}
                          className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs rounded-xl flex flex-row items-center gap-1.5 transition cursor-pointer select-none"
                        >
                          <Rocket className="w-3.5 h-3.5" />
                          <Text>Start This Business</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          onClick={() => handleOpenBlueprint(hustle)}
                          className="px-4 py-2 border border-slate-200 hover:border-slate-300 text-slate-700 font-semibold text-xs rounded-xl flex flex-row items-center gap-1.5 transition cursor-pointer select-none"
                        >
                          <FileText className="w-3.5 h-3.5" />
                          <Text>Complete Business Guide</Text>
                        </TouchableOpacity>
                      </View>
                    </View>
                  ))}
                </View>
              </View>
            )}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

